<ol type = 1>
<li> How pytorch improves training performance</li>
<li> Working with PyTorch's Dataset and DataLoader to build input pipelines and efficient model training</li>
<li> Working with PyTorch to write optimized machine learning code</li>
<li> Using the torch.nn module to implement common deep learning architectures conveniently</li>
<li> Choosing activation functions for artificial NNs</li>
</ol>

Scikit-learn allows us to spread computations over multiple processing unit.<br><br>
Python is limited to execution on one core due to the **Global Interpreter Lock (GIL)**<br><br>
Writing code to target GPUs is not as simple as executing Python code in our interpreter. Special Packages like CUDA and OpenCL help us to write code for GPU.<br><br>

## What is Pytorch?<br>
PyTorch is **scalable** and **multiplatform** programming interface for implementing and running machine learning algorithms.<br><br>
PyTorch supports CUDA-enabled and ROCm GPUs officially.<br><br>
It is built around a computation graph composed of a set of nodes.Each node represents an operation that may have zero or more inputs or outputs.<br><br>
Computation graph is defined implicitly.





## Installing PyTorch

In [ ]:
pip install torch torchvision

In [ ]:
#pip install torch==1.9.0 torchvision==0.10.0

## Creating Tensors in PyTorch

In [ ]:
import torch
import numpy as np
np.set_printoptions(precision = 3)
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype = np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [ ]:
t_ones = torch.ones(2, 3)
t_ones.shape

torch.Size([2, 3])

In [ ]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Creating a tensor of random values

In [ ]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.3549, 0.9999, 0.3307],
        [0.3944, 0.4210, 0.5106]])


### Manipulating the datatype and shape of a tensor
<br>
torch.to() function is used to change the datatype of a tensor to a desired type

---



In [ ]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


#### Transposing a tensor

In [ ]:
t = torch.rand(3,5)
print(t)

tensor([[0.4872, 0.1447, 0.2271, 0.1912, 0.9947],
        [0.6390, 0.2521, 0.9491, 0.8838, 0.5895],
        [0.0792, 0.7070, 0.0942, 0.9234, 0.0285]])


In [ ]:
t_tr = torch.transpose(t, 0, 1)

In [ ]:
print(t_tr)

tensor([[0.4872, 0.6390, 0.0792],
        [0.1447, 0.2521, 0.7070],
        [0.2271, 0.9491, 0.0942],
        [0.1912, 0.8838, 0.9234],
        [0.9947, 0.5895, 0.0285]])


In [ ]:
print(t_tr.shape)

torch.Size([5, 3])


#### Reshaping a Tensor

In [ ]:
t = torch.zeros(30)
print(t)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])


In [ ]:
t_reshape = t.reshape(5,6)
print(t_reshape)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [ ]:
print(t_reshape.shape)

torch.Size([5, 6])


#### Removing unnecessary dimensions

In [ ]:
t = torch.zeros(1, 2, 1, 4, 1)

In [ ]:
print(t)

tensor([[[[[0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.]]]]])


In [ ]:
t_sqz = torch.squeeze(t,2)
print(t_sqz)

tensor([[[[0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.]]]])


In [ ]:
print(t_sqz.shape)

torch.Size([1, 2, 4, 1])


In [ ]:
t = torch.zeros(1, 2, 1, 4, 4)

In [ ]:
print(t)

tensor([[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]]])


### Applying Mathematical operations to tensors

In [ ]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) -1 #tensor with uniform distribution in range[0,1]
print(t1)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])


In [ ]:
t2 = torch.normal(mean = 0, std = 1, size = (5, 2))# tensor with normal distribution
print(t2)

tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [ ]:
#multiplication
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [ ]:
#mean
t4 = torch.mean(t1, axis = 0)#column wise
print(t4)

tensor([-0.1373,  0.2028])


In [ ]:
#sum
t_sum = torch.sum(t1)
print(t_sum)

tensor(0.3273)


In [ ]:
#stadard deviation
t_std = torch.std(t2)
print(t_std)
print(t_std.dtype)

tensor(0.8870)
torch.float32


In [ ]:
#matrix multiplication
t5 = torch.matmul(t1, torch.transpose(t2, 1, 0))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [ ]:
print(torch.transpose(t2, 0, 1))

tensor([[ 0.8590, -0.3406, -1.1948, -0.7627, -0.3245],
        [ 0.7056, -1.2720,  0.0250,  1.3969,  0.2879]])


In [ ]:
print(torch.transpose(t2, 1, 0))

tensor([[ 0.8590, -0.3406, -1.1948, -0.7627, -0.3245],
        [ 0.7056, -1.2720,  0.0250,  1.3969,  0.2879]])


In [ ]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [ ]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [ ]:
# Finding Norm eg L2 norm
norm_t1 = torch.linalg.norm(t1, ord = 2, dim =1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


In [ ]:
np.sqrt(np.sum(np.square(t1.numpy()), axis = 1))#verification of the above norm

array([0.678, 0.508, 1.116, 0.549, 0.185], dtype=float32)

### Split, stack and concatenate tensors<br>
torch.chunk() : to split a single tensor into multiple, equally sized tensors. <br> chunks argument = no. of chunks. <br>
dim argument = desired dimension along which to split the tensor, for this the total size of the input tensor along the desired dimension must be divisible by the desired number of splits.

In [ ]:
torch.manual_seed(2)
t = torch.rand(6)
print(t)

tensor([0.6147, 0.3810, 0.6371, 0.4745, 0.7136, 0.6190])


In [ ]:
t_splits = torch.chunk(t, 3)
print(t_splits)

(tensor([0.6147, 0.3810]), tensor([0.6371, 0.4745]), tensor([0.7136, 0.6190]))


In [ ]:
[item.numpy() for item in t_splits]

[array([0.615, 0.381], dtype=float32),
 array([0.637, 0.474], dtype=float32),
 array([0.714, 0.619], dtype=float32)]

In [ ]:
#If the tensor size is not divisible by the chunks value, the last chunk will be smaller

In [ ]:
torch.manual_seed(1)
t = torch.rand(5)
print(t)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


In [ ]:
t_splits = torch.split(t, split_size_or_sections = [1,2, 2])

In [ ]:
[item.numpy() for item in t_splits]

[array([0.758], dtype=float32),
 array([0.279, 0.403], dtype=float32),
 array([0.735, 0.029], dtype=float32)]

In [ ]:
t = torch.rand(4,5)

In [ ]:
print(t)

tensor([[0.2233, 0.0299, 0.3937, 0.7881, 0.9642],
        [0.1895, 0.6085, 0.9314, 0.8313, 0.8116],
        [0.8553, 0.8163, 0.6291, 0.1581, 0.0801],
        [0.2709, 0.4418, 0.1935, 0.6829, 0.6547]])


In [ ]:
t_splits = torch.split(t, 2, 1)

In [ ]:
[item.numpy() for item in t_splits]

[array([[0.223, 0.03 ],
        [0.189, 0.609],
        [0.855, 0.816],
        [0.271, 0.442]], dtype=float32),
 array([[0.394, 0.788],
        [0.931, 0.831],
        [0.629, 0.158],
        [0.194, 0.683]], dtype=float32),
 array([[0.964],
        [0.812],
        [0.08 ],
        [0.655]], dtype=float32)]

In [ ]:
t_splits = torch.split(t, 2, 0)

In [ ]:
[item.numpy() for item in t_splits]

[array([[0.223, 0.03 , 0.394, 0.788, 0.964],
        [0.189, 0.609, 0.931, 0.831, 0.812]], dtype=float32),
 array([[0.855, 0.816, 0.629, 0.158, 0.08 ],
        [0.271, 0.442, 0.194, 0.683, 0.655]], dtype=float32)]

In [ ]:
t_splits = torch.split(t, 2, -1)
[item.numpy() for item in t_splits]

[array([[0.223, 0.03 ],
        [0.189, 0.609],
        [0.855, 0.816],
        [0.271, 0.442]], dtype=float32),
 array([[0.394, 0.788],
        [0.931, 0.831],
        [0.629, 0.158],
        [0.194, 0.683]], dtype=float32),
 array([[0.964],
        [0.812],
        [0.08 ],
        [0.655]], dtype=float32)]

In [ ]:
#Concatenating tensors
A = torch.ones(3)# a tensor of size 3 with all values as 1
B = torch.zeros(2)# a tensor of size 2 with all values as 0
C = torch.cat([A,B], axis = 0)# concatenation operation
print(C)

tensor([1., 1., 1., 0., 0.])


In [ ]:
C = torch.cat([A,B], axis = -1)# concatenation operation

In [ ]:
print(C)

tensor([1., 1., 1., 0., 0.])


In [ ]:
#stacking
A = torch.ones(3)
B = torch.zeros(3)
S = torch.stack([A, B], axis = 1)
print(S)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])


In [ ]:
S = torch.stack([A, B], axis = 0)
print(S)

tensor([[1., 1., 1.],
        [0., 0., 0.]])


In [ ]:
#For referring other functions use the following documentation
#https://pytorch.org/docs/stable/index.html.

 New Notebook: Working with PyTorch's Dataset and DataLoader to build input pipelines and efficient model training